"""add company

Revision ID: 5a2f9181227a
Revises: f9d597d8951b
Create Date: 2023-04-15 19:59:32.687095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2f9181227a'
down_revision = 'f9d597d8951b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recruiters', sa.Column('name', sa.String(), nullable=False))
    op.add_column('recruiters', sa.Column('company_id', sa.String(), nullable=False))
    op.drop_column('recruiters', 'company_name')
    op.drop_column('recruiters', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiters', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('recruiters', 'company_id')
    op.drop_column('recruiters', 'name')
    op.drop_table('company')
    # ### end Alembic commands ###
